[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/room.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
